{{- if and .Values.kafkaExporter.tls.enabled (not .Values.kafkaExporter.tls.insecureSkipTlsVerify) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kafka-exporter.fullname" . }}
  labels:
    {{- include "kafka-exporter.labels" . | nindent 4 }}
    {{- if .Values.labels }}
    {{ toYaml .Values.labels | nindent 4 }}
    {{- end }}
data:
  ca-file: {{ .Values.kafkaExporter.tls.caFile | b64enc }}
  cert-file: {{ .Values.kafkaExporter.tls.certFile | b64enc }}
  key-file: {{ .Values.kafkaExporter.tls.keyFile | b64enc }}
{{- end }}
