{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kafka-exporter.serviceAccountName" . }}
  labels:
    {{- include "kafka-exporter.labels" . | nindent 4 }}
    {{- if .Values.labels }}
    {{ toYaml .Values.labels | nindent 4 }}
    {{- end }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
