{
 "title": "Kafka Exporter Overview",
 "description": "Kafka resource usage and throughput",
 "tags": [ "Kafka" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(kafka_consumergroup_current_offset, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(kafka_consumergroup_current_offset{job=~\"$job\"}, instance)"
   },
   {
    "name": "consumergroup",
    "label": "consumergroup",
    "query": "label_values(kafka_consumergroup_members,consumergroup)"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(kafka_topic_partition_current_offset{instance='$instance',topic!='__consumer_offsets',topic!='--kafka'}, topic)"
   },
   {
    "name": "partition",
    "label": "Partition",
    "query": "label_values(kafka_topic_partition_current_offset{instance='$instance',topic!='__consumer_offsets',topic!='--kafka'}, partition)"
   }
  ]
 },
 "panels": [
  {
   "title": "Lag by (Consumer Group) Topic:  Partition",
   "type": "graph",
   "description": "Estimation of lag by \nconsumer group, topic, and partition (in ms). This is an estimate of how long it will take for your consumer to catch up to your producer eg a value of 5 minutes is an estimate that, at the current rate of consumption and production, it will take 5 minutes for you consumer to catch up ",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumer_lag_millis{instance=~\"$instance\",topic=~\"$topic\",consumergroup=~\"$consumergroup\"}) by (consumergroup, topic, partition) ",
     "legendFormat": "({{consumergroup}}) {{topic}}: partition-{{partition}}"
    }
   ]
  },
  {
   "title": "Count of Unconsumed Offsets by (Consumer Group) Topic:  Partition",
   "type": "graph",
   "description": "This is a count of the number of offsets your consumer is behind the leading offset for a given topic and partition",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_uncommitted_offsets{instance=~\"$instance\",topic=~\"$topic\",consumergroup=~\"$consumergroup\"}) by (consumergroup, topic, partition) ",
     "legendFormat": "({{consumergroup}}) {{topic}}: partition-{{partition}}"
    }
   ]
  },
  {
   "title": "Rate of messages in per minute by topic",
   "type": "graph",
   "description": "How many messages are produced to a topic per minute",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "messages per minute" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kafka_topic_partition_current_offset{instance=~'$instance', topic=~\"$topic\"}[5m])/5) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages consumed per minute by (Consumer Group) Topic:  Partition",
   "type": "graph",
   "description": "Rate of messages consumed per minute by consumer group, topic, and partition",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kafka_consumergroup_current_offset{instance=~\"$instance\",consumergroup=~\"$consumergroup\",topic=~\"$topic\"}[5m])/5) by (consumergroup, topic, partition)",
     "legendFormat": "({{consumergroup}}) {{topic}}: partition-{{partition}}"
    }
   ]
  },
  {
   "title": "ID of last offset consumed by Consumer Group - Topic - Partition",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_current_offset{instance=~\"$instance\",topic=~\"$topic\",consumergroup=~\"$consumergroup\"}) by (consumergroup, topic, partition) ",
     "legendFormat": "{{consumergroup}} - {{topic}} - {{partition}}"
    }
   ]
  }
 ]
}